### ISSUE TITLE
mprotect failed: Permission denied

### ISSUE THREAD

**Issue by ouchkernel** [utmapp/UTM#2371]
**Describe the issue**
I have tried serval different bootable linux x86_64 ISO and I keep getting `mprotect failed: Permission denied` in the debug.log. During the boot it's also showing `Boot failed: Could not read from CDROM (code 0003)`.

```
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: warning: global PIIX4_PM.disable_s3=1 not used
```

I have tried Ubuntu, Fedora, Oracle Linux with Nvme, IDE and VirtIO. 

**Configuration**

* UTM Version: 2.0.22 (22)
* OS Version: Big Sur 11.2.2 
* Intel or Apple Silicon? Apple Silicon

**Debug log**
```
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -vga none -spice port=4001,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device qxl-vga -smp cpus=1,sockets=1,cores=1,threads=1 -machine q35, -accel tcg,tb-size=1024 -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -boot order=d -m 4096 -device AC97 -name Ubuntu -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device usb-storage,drive=drive0,removable=true -drive if=none,media=cdrom,id=drive0 -drive if=ide,media=disk,id=drive1,file=/Users/john/Library/Containers/com.utmapp.UTM/Data/Documents/Ubuntu.utm/Images/disk-0.qcow2,cache=writethrough -device rtl8139,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 00B4CEC5-8538-4DFF-B31C-78D739AC6456 -rtc base=localtime
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: warning: global PIIX4_PM.disable_s3=1 not used
```

**Upload VM**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict>
		<key>DebugLog</key>
		<true/>
	</dict>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>qxl-vga</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>usb</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>ide</string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>rtl8139</string>
		<key>NetworkEnabled</key>
		<true/>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>AC97</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>x86_64</string>
		<key>BootDevice</key>
		<string>cd</string>
		<key>CPU</key>
		<string>default</string>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>Memory</key>
		<integer>4096</integer>
		<key>SystemUUID</key>
		<string>00B4CEC5-8538-4DFF-B31C-78D739AC6456</string>
		<key>Target</key>
		<string>q35</string>
	</dict>
</dict>
</plist>
```

**Comment by osy86** [comment]
ouch

**Comment by ouchkernel** [comment]
@osy Is there away to have UTM use a different version of qemu? When will UTM uptake the latest version of qemu?  I have built the latest and this issue seems to have been resolved.

**Comment by osy** [comment]
You can try the dev branch for example https://github.com/utmapp/UTM/suites/2256977913/artifacts/46969499

**Comment by jonofmac** [comment]
I am having this issue still in June on the latest version of UTM I can download.

I do not see any dev branch in the project, and for some reason trying to compile from source is failing on M1. Cu

**Comment by ktprograms** [comment]
@ouchkernel Try using something other than the `USB` interface for the removable installation media. `IDE` worked for me when I had this same `Boot failed: Could not read from CDROM (code 0003)`.

**Comment by lukaskirner** [comment]
> @ouchkernel Try using something other than the `USB` interface for the removable installation media. `IDE` worked for me when I had this same `Boot failed: Could not read from CDROM (code 0003)`.
The usage of IDE results into an error

Any solution to this issue?

**Comment by osy** [comment]
Should be fixed on latest version. If the issue persists, please open a new issue with updated debug logs.
