### ISSUE TITLE
UTM on M1 - Windows 10 (21354) is "one time use"

### ISSUE THREAD

**Issue by NosillaCast** [utmapp/UTM#2646]
**Describe the issue**
I can install Windows 10 in UTM and the first time through it boots. If I log out, close the VM and reopen it, I get a BSOD with the beloved `Stop code: 0xc00002e3`. I've created the VM a half dozen times and the Windows crash is 100% repeatable.

**Configuration**
* UTM Version: **2.11 (30)**
* OS Version: **macOS Big Sur 11.3**
* Intel or Apple Silicon? **Apple Silicon**
* Windows 10 Insider Preview version: **Windows10_InsiderPreview_Client_ARM64_en-us_21354.VHDX**

**Crash log**
UTM is not crashing

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

[utm-windows10-m1-debug-nosillacast.txt](https://github.com/utmapp/UTM/files/6743825/utm-windows10-m1-debug-nosillacast.txt)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

Added .txt extensions so GitHub would let me attach the plist:
[config.plist.txt](https://github.com/utmapp/UTM/files/6743831/config.plist.txt)

**Comment by AWTSteve** [comment]
Describe the issue
Seeing the same issue, same stop code, only difference is macOS Big Sur version. 

Configuration

UTM Version: 2.11 (30)
OS Version: macOS Big Sur 11.4
Intel or Apple Silicon? Apple Silicon
Windows 10 Insider Preview version: Windows10_InsiderPreview_Client_ARM64_en-us_21354.VHDX
Crash log
UTM is not crashing

Debug log
For all issues, including crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the QEMU page is Debug Log. Turn it on and save the VM. After you experience the issue, open the VM settings again and select Export Log... and attach it here.

[utm-windows10-m1-debug-awtsteve.txt](https://github.com/utmapp/UTM/files/6744223/utm-windows10-m1-debug-awtsteve.txt)


Upload VM
(Optional) If possible, upload the config.plist inside the .utm. If you do not have this, you can upload the entire .utm but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

Added .txt extensions so GitHub would let me attach the plist:

[config.plist.txt](https://github.com/utmapp/UTM/files/6744242/config.plist.txt)

**Comment by JaheimLee** [comment]
Similar problem! When I finish the SPICE Guest Tools and QEMU Drivers (Windows) installation and shut down the VM, I can't restart it. There is only a gray window. Here is the log:
```
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -vga none -spice port=4001,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device virtio-ramfb -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=2048 -bios /Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd -boot menu=on -m 8192 -device intel-hda -device hda-duplex -name "Windows 11" -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device nvme,drive=drive0,serial=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/jaheimlee/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11.utm/Images/Windows10_InsiderPreview_Client_ARM64_en-us_21354.VHDX,cache=writethrough" -device usb-storage,drive=drive1,removable=true,bootindex=1 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=CE:64:CA:5E:FE:9A,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid DBC44F13-9851-493E-92B5-05F6A025F4E5 -rtc base=localtime
qemu-aarch64-softmmu: -spice port=4001,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off: warning: short-form boolean option 'disable-ticketing' deprecated
Please use disable-ticketing=on instead
```

**Comment by kscheff** [comment]
Same issue on 11.4@M1. Did anybody try to use the recommended .qcow2 image translation before starting?

**Comment by mlwyne** [comment]
I had this same issue, I fixed it by converting the image to qcow2 according to [these steps](https://thatsniceguy.gitbook.io/utmfaq/software-and-vms/misc-tips#vhdx-to-qcow2-conversion)

**Comment by conath** [comment]
Please convert the VHDX to QCOW2 **before** you add it to UTM and especially before you start the VM for the first time.

**Comment by AWTSteve** [comment]
Not sure why this was closed, as I'm still seeing the same issues even after converting the image to qcow2 using dmlwyne's comment. Just to make sure that everything was "virgin", I deleted and reloaded UTM (2.1.1 (30)), got a fresh copy of the Win 10 VHDX file, ran it through the converter to create "Windows10_InsiderPreview_Client_ARM64_en-us_21354.QCOW2", and proceeded with the rest of the regular setup steps. Every time I get the same UTM startup screen and then the same Windows BSOD "Inaccessible Boot Device". 

Any ideas where I'm going wrong? I wrote an article for OWC's blog (https://eshop.macsales.com/blog/72081-utm-virtual-machine-on-m1-mac/) back in March when this was working fine; now I'm considering deleting the article. 

<img width="799" alt="Screen Shot 2021-07-06 at 11 47 10 AM" src="https://user-images.githubusercontent.com/86746595/124645608-df4c4680-de50-11eb-8f4d-11260a74884e.png">
<img width="799" alt="Screen Shot 2021-07-06 at 11 47 38 AM" src="https://user-images.githubusercontent.com/86746595/124645614-e1aea080-de50-11eb-96b6-6203a59a2a60.png">

**Comment by kscheff** [comment]
I used the virgin windows image, but following the instruction I have an NVMe boot device:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/8903302/124648260-5ad0e680-de97-11eb-859e-d91af42ee914.png">

**Comment by AWTSteve** [comment]
Thank you! I was just re-elected as president of the blithering idiot club. I had ignored the one step where you change to an NVMe boot device. All seems to be working well now. I'll update my article with the QCOW2 conversion step. Appreciate your help!

**Comment by NosillaCast** [comment]
I was a charter member of the blithering idiot club (I forgot NVMe a few times myself even though @AWTSteve's instructions clearly said to choose NVMe).  

fater doing the qcow2 conversion of a fresh download of the VHDX from Microsoft, and ensuring I have NVMe selected, I can't get past the black "Start boot option" screen.

<img width="800" alt="black boot screen" src="https://user-images.githubusercontent.com/12651464/124664296-1413ca00-de60-11eb-94e9-58c01b684c32.png">
<img width="900" alt="utm drives" src="https://user-images.githubusercontent.com/12651464/124665287-62759880-de61-11eb-9541-0da19ada7010.png">

I got this far only by changing the number of CPU cores in the System setting from blank to 8, because I was getting an error saying it was trying to use too many cores.

I've played around with changing which QEMU on the System tab, System dropdown, currently using virt-6.0.  Does that matter?

<img width="821" alt="system cores" src="https://user-images.githubusercontent.com/12651464/124664507-67861800-de60-11eb-8561-f61661d6fa82.png">

The only thing I know is different from Steve's setup is that I didn't download a fresh version of UTM 2.1.1 (30) because I finally got Ubuntu working in it and I hate to destroy that work. The only thing I seem to be able to do is interrupt the boot screen with escape and then access the boot manager, but I haven't identified any problems with what I see.

<img width="640" alt="boot manager" src="https://user-images.githubusercontent.com/12651464/124665569-b97b6d80-de61-11eb-8cf5-c20dbfad556c.png">
