### ISSUE TITLE
Purple Screen Reboot on iOS/iPadOS 15 when using OpenGL graphics

### ISSUE THREAD

**Issue by HenryQuan** [utmapp/UTM#2743]
**Describe the issue**
Booting debian-10-4-xfce downloaded from the gallery on iOS 15.0 Beta 5 results in a purple screen and reboot. This is very consistent and happens all the time.

**Configuration**
* UTM Version: 2.2.0
* OS Version: 15.0 Beta 5
* Device Model: iPad Pro 11 inch 3rd gen
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? iOS App Signer & iosdeploy

**Crash log**
[panic.zip](https://github.com/utmapp/UTM/files/6974877/panic.zip)

**Debug log**
[debug.log.zip](https://github.com/utmapp/UTM/files/6974909/debug.log.zip)

**Upload VM**
https://mac.getutm.app/gallery/debian-10-4-xfce. This one from the gallery is used with no modifications.

**Comment by HenryQuan** [comment]
By using https://mac.getutm.app/gallery/debian-10-4-ldxe, I can produce the same issue.

**Comment by HenryQuan** [comment]
This seems to be an issue with the beta. Same VM works on 2.1.2.

**Comment by coreycusick** [comment]
I have the same issue with Ubuntu arm. It appears to be something to do with UTM taking all the ram due to a possible memory leak when an OS uses OpenGL. Hasn’t yet been fixed

**Comment by HubertZhang** [comment]
I adjusted memory from 2GB to 3GB and `virtio-rambf` works without purple screen. However, UTM crashed later when I tried to open an app in Ubuntu.

qemu logs ends with following lines

```
qemu-system: spice_iosurface_create: IOSurfaceCreate failed
qemu_spice_gl_scanout_texture: failed to get fd for texture
```

**Comment by conath** [comment]
This memory issue with the UTM 2.2.0 beta has been addressed, in beta 2.2.1.

**Comment by HubertZhang** [comment]
Still encountered such problem in beta 2.2.2, iPadOS 15 beta 8..

**Comment by HubertZhang** [comment]
I ran UTM through Xcode and used master branch. Before system crash, RAM didn't increase so much according to Xcode debug session panel...

Please let me know if you need any log or more information.

**Comment by conath** [comment]
To be clear, @HubertZhang your iPad reboots entirely. Not just UTM?

**Comment by HubertZhang** [comment]
Yes, my iPad reboots entirely.

I tried master version on iPadOS 15 and encountered same issue..

**Comment by osy** [comment]
I too am hitting this error on iOS 15 and the kicker is that I google to see if there's any way to get any debug info out of the iPhone and guess what this issue shows up as the top result...

**Comment by conath** [comment]
@osy I might be stating the obvious here but have you tried [viewing the iOS system log with Console app](https://support.apple.com/guide/console/log-messages-cnsl1012/mac) on Mac?

**Comment by osy** [comment]
So I updated ANGLE and virglrenderer to the latest commit and some preliminary tests shows that it's no longer crashing.

**Comment by HubertZhang** [comment]
UTM still crashed when using master version UTM and 3.0.0-beta sysroot image...

Panic report is attached:
[panic-full-2022-01-04-030054.000.ips.zip](https://github.com/utmapp/UTM/files/7803706/panic-full-2022-01-04-030054.000.ips.zip)

**Comment by DownGnu** [comment]
[This is my log](https://drive.google.com/file/d/1-m7h7nTXo_G-n5bXhFvQycHXAGLXWsJk/view?usp=drivesdk)

**Comment by osy** [comment]
I think I might have found the issue. It's a race condition in IOMobileFramebuffer

1. QEMU calls IOSurfaceCreate -> IOSurface `S` is created
1. ... IOSurfaceRootUserClient::s_lookup_surface -> creates a IOSurfaceClient `SC`
1. ... IOSurfaceRootUserClient::set_surface_handle -> associates `X` with IOSurfaceClient `SC`
2. QEMU calls IOSurfaceGetID(`S`) -> returns id `X`
3. QEMU passes `X` to UTM through write on shared FD
4. QEMU is done with the surface and calls CFRelease(`S`)
4. ... IOSurfaceRootUserClient::s_release_surface -> frees IOSurfaceClient `SC` and id `X`
5. QEMU calls IOSurfaceCreate
5. ... IOSurfaceRootUserClient::s_create_surface -> allocates IOSurface `T` which reuses id `X`
5. ... IOSurfaceRootUserClient::s_create_surface -> waits on a lock on the client
6. UTM reads `X` from the shared FD and calls IOSurfaceLookup(`X`)
6. ... IOSurfaceRootUserClient::s_lookup_surface -> gets lock on client
6. ... IOSurfaceRootUserClient::s_lookup_surface -> finds IOSurface `T` (not `S` as expected)
6. ... IOSurfaceRootUserClient::s_lookup_surface -> creates a IOSurfaceClient `TC1` for `T`
6. ... IOSurfaceRootUserClient::set_surface_handle -> associates `X` with IOSurfaceClient `TC1`
6. ... IOSurfaceRootUserClient::s_lookup_surface -> releases lock on client
7. QEMU calls IOSurfaceCreate (continued from 10)
7. ... IOSurfaceRootUserClient::s_create_surface -> gets lock on client
7. ... IOSurfaceRootUserClient::s_create_surface -> creates a IOSurfaceClient `TC2` for `T`
7. ... IOSurfaceRootUserClient::set_surface_handle -> associates `X` with IOSurfaceClient `TC2`
7. ... BUT id `X` is already referencing `TC1`, **panic**!

The issue here is that the client lock isn't held by QEMU's thread (calling into IOMFB) between 9 and 18. That means another thread (UTM calling into IOMFB) can use IOSurfaceLookup to grab `T` and create `TC2` and associate it with id `X` before the first thread (that created `T`) is able to create `TC1` and associate it with id `X`.

The fix is to ensure we do not ever call IOSurfaceLookup on a stale `X` by making sure we retain `S` until after UTM safely retains it.

**Comment by DownGnu** [comment]
Oh wow, then will this issue be resolved on the next beta?

**Comment by HubertZhang** [comment]
Using GPU supported device no longer causes purple screen on fcc1dea version! Hooray!

**Comment by dk335** [comment]
Tuneskit ios system recovery can help reset an iphone. It has a feature for entering and exiting from recovery mode in one click. Maybe this can fix the problem.
