### ISSUE TITLE
Mac99 PPC and PPC64 not booting and crashing UTM on iOS

### ISSUE THREAD

**Issue by Vishram1123** [utmapp/UTM#3041]
**Describe the issue**
When creating a Mac99 PPC or PPC64 machine in UTM SE (with or without a drive, screamer, or 1 cores set in advanced config), the vm immediately crashes and kills UTM SE. 

**Configuration (required)**
* UTM Version: 2.2.0 SE
* OS Version: 15.0b6
* Device Model: iPhone 12 Mini
* Is it jailbroken: No
* How did you install UTM: TestFlight 

**Crash log**

<details> <summary>Crash Log</summary>

```

SE","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.0 (19A5325f)","incident_id":"BAE401F8-C4B0-48D7-A501-69ED471BF753","name":"UTM SE","is_beta":1}
{
  "uptime" : 10000,
  "procLaunch" : "2021-08-24 08:51:19.7649 -0400",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone13,1",
  "procStartAbsTime" : 244536692253,
  "coalitionID" : 827,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.0",
    "releaseType" : "Beta",
    "build" : "19A5325f"
  },
  "captureTime" : "2021-08-24 08:51:31.2954 -0400",
  "incident" : "BAE401F8-C4B0-48D7-A501-69ED471BF753",
  "bug_type" : "309",
  "pid" : 972,
  "procExitAbsTime" : 244813372479,
  "cpuType" : "ARM-64",
  "procName" : "UTM SE",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/5A86C5A5-98D7-4A06-82EE-DD64741C419F\/UTM SE.app\/UTM SE",
  "bundleInfo" : {"CFBundleShortVersionString":"2.2.0","CFBundleVersion":"32","CFBundleIdentifier":"com.utmapp.UTM-SE","DTAppStoreToolsBuild":"12E506"},
  "storeInfo" : {"itemID":"1564628856","storeCohortMetadata":"2|date=1629574200000&sf=143441&tid=89a29b11fc714c7acf53bdff8be3105e8f7076ad8c5ba573fe9cd785998da0d4&ttype=e","entitledBeta":true,"deviceIdentifierForVendor":"73DB45F8-3198-46FF-A4D4-065DBB53D068","softwareVersionExternalIdentifier":"74088285","applicationVariant":"1:iPhone13,1:14","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.utmapp.UTM-SE",
  "isBeta" : 1,
  "basebandVersion" : "2.09.10",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "faultingThread" : 10,
  "threads" : [{"id":160895,"queue":"com.apple.main-thread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":5004,"imageIndex":2},{"imageOffset":5349336,"imageIndex":3},{"imageOffset":2719516,"imageIndex":3},{"imageOffset":2355640,"imageIndex":4},{"imageOffset":1493972,"imageIndex":4},{"imageOffset":1367952,"imageIndex":4},{"imageOffset":959684,"imageIndex":5},{"imageOffset":952760,"imageIndex":5},{"imageOffset":104996,"imageIndex":6}]},{"id":160896,"frames":[{"imageOffset":3912,"imageIndex":7}]},{"id":160897,"frames":[{"imageOffset":3912,"imageIndex":7}]},{"id":160898,"frames":[{"imageOffset":3912,"imageIndex":7}]},{"id":160899,"queue":"com.apple.root.background-qos","frames":[{"imageOffset":5568,"imageIndex":0},{"imageOffset":16096,"imageIndex":8},{"imageOffset":17816,"imageIndex":8},{"imageOffset":65732,"imageIndex":5},{"imageOffset":7172,"imageIndex":8},{"imageOffset":14672,"imageIndex":8},{"imageOffset":86120,"imageIndex":8},{"imageOffset":87912,"imageIndex":8},{"imageOffset":4468,"imageIndex":7},{"imageOffset":3920,"imageIndex":7}]},{"id":160900,"frames":[{"imageOffset":3912,"imageIndex":7}]},{"id":160901,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":102884,"imageIndex":9},{"imageOffset":370584,"imageIndex":9},{"imageOffset":4796652,"imageIndex":3},{"imageOffset":428592,"imageIndex":9},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":160902,"frames":[{"imageOffset":3912,"imageIndex":7}]},{"id":161051,"frames":[{"imageOffset":19396,"imageIndex":0},{"imageOffset":441888,"imageIndex":10},{"imageOffset":368032,"imageIndex":10},{"imageOffset":358060,"imageIndex":10},{"imageOffset":359704,"imageIndex":10},{"imageOffset":102744,"imageIndex":5},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161052,"frames":[{"imageOffset":7012,"imageIndex":0},{"imageOffset":20220,"imageIndex":11},{"imageOffset":598480,"imageIndex":10},{"imageOffset":34194240,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"triggered":true,"id":161053,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":4793341110},{"value":6098397040},{"value":10},{"value":0},{"value":4838065066000710092},{"value":4838065060986014156},{"value":2},{"value":4294967293},{"value":0},{"value":0},{"value":1},{"value":2},{"value":328},{"value":6098399232},{"value":0},{"value":6},{"value":30735},{"value":6098399456},{"value":4793944843},{"value":4793945444},{"value":10801336928},{"value":2},{"value":1},{"value":40},{"value":4711786928}],"flavor":"ARM_THREAD_STATE64","lr":{"value":8353264692},"cpsr":{"value":1073745920},"fp":{"value":6098397120},"sp":{"value":6098397088},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7387929016,"matchesCrashFrame":1},"far":{"value":4715495424}},"frames":[{"imageOffset":31160,"imageIndex":0},{"imageOffset":29748,"imageIndex":7},{"imageOffset":130916,"imageIndex":11},{"imageOffset":34570376,"imageIndex":12},{"imageOffset":34170208,"imageIndex":12},{"imageOffset":34168172,"imageIndex":12},{"imageOffset":32518592,"imageIndex":12},{"imageOffset":32534656,"imageIndex":12},{"imageOffset":32519068,"imageIndex":12},{"imageOffset":32492468,"imageIndex":12},{"imageOffset":31257584,"imageIndex":12},{"imageOffset":344824,"imageIndex":12},{"imageOffset":31241824,"imageIndex":12},{"imageOffset":1480108,"imageIndex":12},{"imageOffset":1493608,"imageIndex":12},{"imageOffset":349252,"imageIndex":5},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161054,"name":"com.apple.CFStream.LegacyThread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":1079928,"imageIndex":1},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161055,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":2599120,"imageIndex":13},{"imageOffset":428592,"imageIndex":9},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161056,"frames":[{"imageOffset":179588,"imageIndex":0},{"imageOffset":42420,"imageIndex":7},{"imageOffset":34150536,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161057,"frames":[{"imageOffset":19396,"imageIndex":0},{"imageOffset":441888,"imageIndex":10},{"imageOffset":368032,"imageIndex":10},{"imageOffset":358060,"imageIndex":10},{"imageOffset":359704,"imageIndex":10},{"imageOffset":32665184,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161058,"frames":[{"imageOffset":9964,"imageIndex":0},{"imageOffset":9352,"imageIndex":7},{"imageOffset":38188,"imageIndex":7},{"imageOffset":33536,"imageIndex":7},{"imageOffset":34158984,"imageIndex":12},{"imageOffset":1379140,"imageIndex":12},{"imageOffset":30405312,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161059,"frames":[{"imageOffset":9964,"imageIndex":0},{"imageOffset":9352,"imageIndex":7},{"imageOffset":38188,"imageIndex":7},{"imageOffset":33536,"imageIndex":7},{"imageOffset":34158984,"imageIndex":12},{"imageOffset":1379140,"imageIndex":12},{"imageOffset":30405312,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161060,"frames":[{"imageOffset":9964,"imageIndex":0},{"imageOffset":9352,"imageIndex":7},{"imageOffset":38188,"imageIndex":7},{"imageOffset":33536,"imageIndex":7},{"imageOffset":34158984,"imageIndex":12},{"imageOffset":1379140,"imageIndex":12},{"imageOffset":30405312,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161061,"frames":[{"imageOffset":9964,"imageIndex":0},{"imageOffset":9352,"imageIndex":7},{"imageOffset":38188,"imageIndex":7},{"imageOffset":33536,"imageIndex":7},{"imageOffset":34158984,"imageIndex":12},{"imageOffset":1379140,"imageIndex":12},{"imageOffset":30405312,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161062,"frames":[{"imageOffset":9964,"imageIndex":0},{"imageOffset":9352,"imageIndex":7},{"imageOffset":38188,"imageIndex":7},{"imageOffset":33536,"imageIndex":7},{"imageOffset":34158984,"imageIndex":12},{"imageOffset":1379140,"imageIndex":12},{"imageOffset":30405312,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]},{"id":161063,"frames":[{"imageOffset":9964,"imageIndex":0},{"imageOffset":9352,"imageIndex":7},{"imageOffset":38188,"imageIndex":7},{"imageOffset":33536,"imageIndex":7},{"imageOffset":34158984,"imageIndex":12},{"imageOffset":1379140,"imageIndex":12},{"imageOffset":30405312,"imageIndex":12},{"imageOffset":34161524,"imageIndex":12},{"imageOffset":6752,"imageIndex":7},{"imageOffset":3932,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7387897856,
    "size" : 212992,
    "uuid" : "061cf881-ce66-3b63-b9cc-4e266e382de7",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6473113600,
    "size" : 4538368,
    "uuid" : "f0ad1367-1bae-3957-a3f2-091e049db82d",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6934233088,
    "size" : 36864,
    "uuid" : "c45c68be-4df0-35ea-962f-27f5512ba09c",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6511550464,
    "size" : 25665536,
    "uuid" : "e498d63d-b35e-3a36-a2cf-688254c73835",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6601125888,
    "size" : 16912384,
    "uuid" : "1269aa5d-0334-3702-a396-3c33969dfb13",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/SwiftUI",
    "name" : "SwiftUI"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4374200320,
    "size" : 3194880,
    "uuid" : "fabe74c5-0889-3ad1-bb69-b1919290cdbf",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/5A86C5A5-98D7-4A06-82EE-DD64741C419F\/UTM SE.app\/UTM SE",
    "name" : "UTM SE"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4381474816,
    "size" : 360448,
    "uuid" : "8836f397-3370-320c-baed-76edf7977ab0",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8353234944,
    "size" : 49152,
    "uuid" : "4ef97b53-dd38-3d5b-bb8d-6edd490355af",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6470000640,
    "size" : 286720,
    "uuid" : "70fbc63e-c446-3bd3-a3bd-6f022317469b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6498451456,
    "size" : 3166208,
    "uuid" : "b2622a6a-ae26-3f10-b9cb-19c1c113f29b",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4395696128,
    "size" : 1589248,
    "uuid" : "a63140f0-57dd-3231-94ea-22ca8d2db79b",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/5A86C5A5-98D7-4A06-82EE-DD64741C419F\/UTM SE.app\/Frameworks\/glib-2.0.0.framework\/glib-2.0.0",
    "name" : "glib-2.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6655918080,
    "size" : 520192,
    "uuid" : "c805b686-e4d3-3961-9dcf-03ba2695fd65",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4758634496,
    "size" : 39665664,
    "uuid" : "30d5c210-fafe-37c4-b178-786655b27263",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/5A86C5A5-98D7-4A06-82EE-DD64741C419F\/UTM SE.app\/Frameworks\/qemu-ppc64-softmmu.framework\/qemu-ppc64-softmmu",
    "name" : "qemu-ppc64-softmmu"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6481592320,
    "size" : 5001216,
    "uuid" : "9534b29d-1aad-3a47-ba01-11aa2bfcc10f",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/CFNetwork",
    "name" : "CFNetwork"
  }
],
  "sharedCache" : {
  "base" : 6469681152,
  "size" : 2456666112,
  "uuid" : "15989fc7-7698-3890-b8bf-688a90e6777c"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=911.8M resident=0K(0%) swapped_out_or_unallocated=911.8M(100%)\nWritable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                    5936K       32 \nColorSync                          128K        8 \nCoreAnimation                     1168K       51 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           602.9M      288 \nMALLOC guard page                  192K       12 \nSQLite page cache                  128K        2 \nSTACK GUARD                        336K       21 \nStack                             11.6M       21 \nVM_ALLOCATE                       11.3M       61 \nVM_ALLOCATE (reserved)           640.2M       50         reserved VM address space (unallocated)\n__AUTH                            4616K      540 \n__AUTH_CONST                      26.0M      709 \n__DATA                            29.5M      775 \n__DATA_CONST                      27.7M      749 \n__DATA_DIRTY                      2839K      590 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       195.3M       79 \n__OBJC_CONST                      6673K      512 \n__OBJC_RO                         90.5M        1 \n__OBJC_RW                         3392K        1 \n__TEXT                           716.5M      801 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      164.0M       25 \nshared memory                     2096K        5 \n===========                     =======  ======= \nTOTAL                              2.5G     5347 \nTOTAL, minus reserved VM space     1.9G     5347 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_HAMMER" : "610950f91cbd7a245337216e"
      },
      "deploymentId" : 250000110
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "60ef663fa2f864203caf575c"
      },
      "deploymentId" : 250000055
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 250000013
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "610c8690fc54bc338984020b"
      },
      "deploymentId" : 250000156
    },
    {
      "rolloutId" : "60509d56f2766876dee21c11",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "610c8c6137f5d11121dcd240",
        "SIRI_UNDERSTANDING_NL" : "610c8c6837f5d11121dcd258",
        "SIRI_UNDERSTANDING_MORPHUN" : "610c8c5afc54bc338984030c",
        "SIRI_EXPERIENCE_CAM" : "610c8c6dfc54bc338984033b"
      },
      "deploymentId" : 250000346
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 250000007
    },
    {
      "rolloutId" : "602c34a3046661000c9ebdde",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "611add10fc54bc3389840987"
      },
      "deploymentId" : 250000364
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "611ad37537f5d11121dcd81b"
      },
      "deploymentId" : 250000164
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "577038e4-446f-429a-899c-2e92b4b1dc9d",
      "experimentId" : "60c785f07aa5af21f0101872",
      "deploymentId" : 500000001
    },
    {
      "treatmentId" : "f2b19ff9-b1e3-42c4-8ad0-2ad670b8a61c",
      "experimentId" : "60c7880b7aa5af21f0101873",
      "deploymentId" : 500000001
    },
    {
      "treatmentId" : "29062ccf-0f10-45b3-8469-e7bdecfddcfa",
      "experimentId" : "606613a1c82cac25f0368de9",
      "deploymentId" : 500000015
    }
  ]
}
}

```

</details>

**Debug log**
<details> <summary>Debug</summary> 

```

-[CSConnection finishInit]:270
-[CSInput initWithSession:]:293
2021-08-24 08:51:17.813 UTM SE[952:155347] -[CSConnection finishInit]:270
2021-08-24 08:51:17.813 UTM SE[952:155347] -[CSInput initWithSession:]:293
-[CSSession initWithSession:]:294
2021-08-24 08:51:17.813 UTM SE[952:155347] -[CSSession initWithSession:]:294
Running:  -L "/private/var/containers/Bundle/Application/5A86C5A5-98D7-4A06-82EE-DD64741C419F/UTM SE.app/qemu" -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/572B0F15-5518-4E2D-8489-F710011D321C/tmp/240A0923-2B22-4438-B242-95866E5C3F57.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -device VGA -smp cpus=6,sockets=1,cores=6,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=128 -boot menu=on -m 512 -audiodev coreaudio,id=audio0 -name "Virtual Machine 3" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device rtl8139,mac=CA:91:E1:2B:D2:F3,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 240A0923-2B22-4438-B242-95866E5C3F57 -rtc base=localtime
Loading qemu-ppc64-softmmu.framework/qemu-ppc64-softmmu
2021-08-24 08:51:17.815 UTM SE[952:155347] Running:  -L "/private/var/containers/Bundle/Application/5A86C5A5-98D7-4A06-82EE-DD64741C419F/UTM SE.app/qemu" -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/572B0F15-5518-4E2D-8489-F710011D321C/tmp/240A0923-2B22-4438-B242-95866E5C3F57.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -device VGA -smp cpus=6,sockets=1,cores=6,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=128 -boot menu=on -m 512 -audiodev coreaudio,id=audio0 -name "Virtual Machine 3" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device rtl8139,mac=CA:91:E1:2B:D2:F3,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 240A0923-2B22-4438-B242-95866E5C3F57 -rtc base=localtime
2021-08-24 08:51:17.815 UTM SE[952:155347] Loading qemu-ppc64-softmmu.framework/qemu-ppc64-softmmu
Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP connection failed, retries left: 29
2021-08-24 08:51:17.929 UTM SE[952:155371] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2021-08-24 08:51:17.929 UTM SE[952:155371] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2021-08-24 08:51:17.929 UTM SE[952:155371] QMP connection failed, retries left: 29
QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP connection failed, retries left: 28
2021-08-24 08:51:17.929 UTM SE[952:155371] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2021-08-24 08:51:17.929 UTM SE[952:155371] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2021-08-24 08:51:17.929 UTM SE[952:155371] QMP connection failed, retries left: 28
audio: Unknown audio driver `coreaudio'
audio: warning: Using timer based audio emulation
audio: Device Screamer Sound Chip: audiodev default parameter is deprecated, please specify audiodev=audio0

```

</details>

**Comment by osy** [comment]
I think just disabling audio should fix it.

**Comment by Vishram1123** [comment]
As I mentioned earlier, this issue is still present even if screamer is disabled. PPC64 works if I disable screamer (I removed via=pmu and set cores to 1), and I can even use 32 bit emulation if I set the processor to ppc32

**Comment by osy** [comment]
I mean you can uncheck enable audio.

**Comment by Vishram1123** [comment]
I did, and it still did that

**Comment by Vishram1123** [comment]
I will post a video shortly

**Comment by osy** [comment]
I think debug.log is good enough.

**Comment by Vishram1123** [comment]
<details><summary> 2nd debug.log 
</summary>

-[CSConnection finishInit]:270
2021-08-30 19:26:11.209 UTM SE[3312:840377] -[CSConnection finishInit]:270
-[CSInput initWithSession:]:293
2021-08-30 19:26:11.209 UTM SE[3312:840377] -[CSInput initWithSession:]:293
-[CSSession initWithSession:]:294
2021-08-30 19:26:11.210 UTM SE[3312:840377] -[CSSession initWithSession:]:294
Running:  -L "/private/var/containers/Bundle/Application/62DB6D2E-E078-4E2D-9ED4-5A867AE00248/UTM SE.app/qemu" -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/E7985A70-D3D7-4C22-9EF1-66D532322E63/tmp/7F7AA38B-145F-4E5F-AA6C-E379A103D9BD.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -device VGA -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=256 -boot menu=on -m 1024 -name "Virtual Machine 2" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device rtl8139,mac=B2:0B:05:C1:B0:90,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 7F7AA38B-145F-4E5F-AA6C-E379A103D9BD -rtc base=localtime
Loading qemu-ppc-softmmu.framework/qemu-ppc-softmmu
2021-08-30 19:26:11.211 UTM SE[3312:840377] Running:  -L "/private/var/containers/Bundle/Application/62DB6D2E-E078-4E2D-9ED4-5A867AE00248/UTM SE.app/qemu" -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/E7985A70-D3D7-4C22-9EF1-66D532322E63/tmp/7F7AA38B-145F-4E5F-AA6C-E379A103D9BD.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -device VGA -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=256 -boot menu=on -m 1024 -name "Virtual Machine 2" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device rtl8139,mac=B2:0B:05:C1:B0:90,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 7F7AA38B-145F-4E5F-AA6C-E379A103D9BD -rtc base=localtime
2021-08-30 19:26:11.211 UTM SE[3312:840377] Loading qemu-ppc-softmmu.framework/qemu-ppc-softmmu
Connected to stream 0x282aab8d0
QMP connection successful! (readStream:1)
Connected to stream 0x282aab330
QMP connection successful! (readStream:0)
2021-08-30 19:26:11.302 UTM SE[3312:841452] Connected to stream 0x282aab8d0
2021-08-30 19:26:11.302 UTM SE[3312:841452] QMP connection successful! (readStream:1)
2021-08-30 19:26:11.302 UTM SE[3312:841452] Connected to stream 0x282aab330
2021-08-30 19:26:11.302 UTM SE[3312:841452] QMP connection successful! (readStream:0)
Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
Debug JSON send -> {
    execute = "qmp_capabilities";
}
2021-08-30 19:26:11.302 UTM SE[3312:841515] Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
2021-08-30 19:26:11.303 UTM SE[3312:841311] Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
2021-08-30 19:26:11.303 UTM SE[3312:841311] Debug JSON send -> {
    execute = "qmp_capabilities";
}
Debug JSON recieved <- {
    return =     {
    };
}
2021-08-30 19:26:11.307 UTM SE[3312:841452] Debug JSON recieved <- {
    return =     {
    };
}
qemuQmpDidConnect
2021-08-30 19:26:11.307 UTM SE[3312:841311] qemuQmpDidConnect
cs_channel_new:163
2021-08-30 19:26:11.333 UTM SE[3312:841311] cs_channel_new:163
qemu-system: warning: GSpice: main-1:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "\Ufffd";
        };
        server =         {
            family = unix;
            host = "";
            port = "\Ufffd";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 334646;
        seconds = 1630365971;
    };
}
2021-08-30 19:26:11.334 UTM SE[3312:841515] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "\Ufffd";
        };
        server =         {
            family = unix;
            host = "";
            port = "\Ufffd";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 334646;
        seconds = 1630365971;
    };
}
Debug JSON send -> {
    execute = cont;
}
qemu-system: info: main channel: opened
2021-08-30 19:26:11.342 UTM SE[3312:841630] Debug JSON send -> {
    execute = cont;
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 1;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 342466;
        seconds = 1630365971;
    };
}
2021-08-30 19:26:11.342 UTM SE[3312:841515] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 1;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 342466;
        seconds = 1630365971;
    };
}
Debug JSON recieved <- {
    event = RESUME;
    timestamp =     {
        microseconds = 342874;
        seconds = 1630365971;
    };
}
Debug JSON recieved <- {
    return =     {
    };
}
2021-08-30 19:26:11.342 UTM SE[3312:841452] Debug JSON recieved <- {
    event = RESUME;
    timestamp =     {
        microseconds = 342874;
        seconds = 1630365971;
    };
}
2021-08-30 19:26:11.343 UTM SE[3312:841452] Debug JSON recieved <- {
    return =     {
    };
}
qemuHasResumed
2021-08-30 19:26:11.343 UTM SE[3312:841311] qemuHasResumed
resizing to (375.000000, 812.000000)
2021-08-30 19:26:11.343 UTM SE[3312:840377] resizing to (375.000000, 812.000000)
cs_channel_new:172
2021-08-30 19:26:11.343 UTM SE[3312:841630] cs_channel_new:172
qemu-system: warning: GSpice: display-2:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
qemu-system: warning: GSpice: inputs-3:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 344143;
        seconds = 1630365971;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 344187;
        seconds = 1630365971;
    };
}
2021-08-30 19:26:11.344 UTM SE[3312:841452] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 344143;
        seconds = 1630365971;
    };
}
2021-08-30 19:26:11.344 UTM SE[3312:841452] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 344187;
        seconds = 1630365971;
    };
}


</details>

Video: [https://drive.google.com/file/d/1cNoVBjY3gQgh9r_UBRqSEwyfb6PSPDOn/view?usp=drivesdk](https://drive.google.com/file/d/1cNoVBjY3gQgh9r_UBRqSEwyfb6PSPDOn/view?usp=drivesdk)

**Comment by osy** [comment]
I see, that’s different from the first debug log. You should get a crash log (the log you attached in the first post is not a crash log, it’s just an analytics log, look for a new entry created after the crash and it should have the time stamp in the name).

**Comment by Vishram1123** [comment]
Crash log:
<details>

cohort":"2|date=1630020600000&sf=143441&tid=89a29b11fc714c7acf53bdff8be3105e8f7076ad8c5ba573fe9cd785998da0d4&ttype=e","app_name":"UTM SE","app_version":"2.2.1","timestamp":"2021-08-31 09:00:39.00 -0400","slice_uuid":"718df039-9948-3810-ad3f-e03df0869ae1","adam_id":"1564628856","build_version":"33","platform":2,"bundleID":"com.utmapp.UTM-SE","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.0 (19A5325f)","incident_id":"8297C5FB-C0B4-4AD5-AA07-FA04106B16BF","name":"UTM SE","is_beta":1}
{
  "uptime" : 140000,
  "procLaunch" : "2021-08-30 21:06:01.7599 -0400",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone13,1",
  "procStartAbsTime" : 2774526134490,
  "coalitionID" : 2039,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.0",
    "releaseType" : "Beta",
    "build" : "19A5325f"
  },
  "captureTime" : "2021-08-31 09:00:38.4940 -0400",
  "incident" : "8297C5FB-C0B4-4AD5-AA07-FA04106B16BF",
  "bug_type" : "309",
  "pid" : 3495,
  "procExitAbsTime" : 3478324879936,
  "cpuType" : "ARM-64",
  "procName" : "UTM SE",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/62DB6D2E-E078-4E2D-9ED4-5A867AE00248\/UTM SE.app\/UTM SE",
  "bundleInfo" : {"CFBundleShortVersionString":"2.2.1","CFBundleVersion":"33","CFBundleIdentifier":"com.utmapp.UTM-SE","DTAppStoreToolsBuild":"12E506"},
  "storeInfo" : {"itemID":"1564628856","storeCohortMetadata":"2|date=1630020600000&sf=143441&tid=89a29b11fc714c7acf53bdff8be3105e8f7076ad8c5ba573fe9cd785998da0d4&ttype=e","entitledBeta":true,"deviceIdentifierForVendor":"73DB45F8-3198-46FF-A4D4-065DBB53D068","softwareVersionExternalIdentifier":"74907471","applicationVariant":"1:iPhone13,1:14","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.utmapp.UTM-SE",
  "isBeta" : 1,
  "basebandVersion" : "2.09.10",
  "vmRegionInfo" : "0xffffffffffffffff is not in any region.  Bytes after previous region: 18446743592673214464  \n      REGION TYPE                 START - END      [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)     1000000000-7000000000 [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  \n      UNUSED SPACE AT END",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0xffffffffffffffff","rawCodes":[1,-1],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0xffffffffffffffff"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":3495},
  "vmregioninfo" : "0xffffffffffffffff is not in any region.  Bytes after previous region: 18446743592673214464  \n      REGION TYPE                 START - END      [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)     1000000000-7000000000 [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  \n      UNUSED SPACE AT END",
  "faultingThread" : 15,
  "threads" : [{"id":879514,"queue":"com.apple.main-thread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":5004,"imageIndex":2},{"imageOffset":5349336,"imageIndex":3},{"imageOffset":2719516,"imageIndex":3},{"imageOffset":2355640,"imageIndex":4},{"imageOffset":1493972,"imageIndex":4},{"imageOffset":1367952,"imageIndex":4},{"imageOffset":959572,"imageIndex":5},{"imageOffset":952648,"imageIndex":5},{"imageOffset":104996,"imageIndex":6}]},{"id":879586,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":102884,"imageIndex":7},{"imageOffset":370584,"imageIndex":7},{"imageOffset":4796652,"imageIndex":3},{"imageOffset":428592,"imageIndex":7},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":879587,"frames":[{"imageOffset":3912,"imageIndex":8}]},{"id":1107315,"frames":[{"imageOffset":3912,"imageIndex":8}]},{"id":1107316,"queue":"com.apple.root.background-qos","frames":[{"imageOffset":5568,"imageIndex":0},{"imageOffset":16096,"imageIndex":9},{"imageOffset":17816,"imageIndex":9},{"imageOffset":64872,"imageIndex":5},{"imageOffset":7172,"imageIndex":9},{"imageOffset":14672,"imageIndex":9},{"imageOffset":86120,"imageIndex":9},{"imageOffset":87912,"imageIndex":9},{"imageOffset":4468,"imageIndex":8},{"imageOffset":3920,"imageIndex":8}]},{"id":1107352,"name":"AVAudioSession Notify Thread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":25352,"imageIndex":10},{"imageOffset":64868,"imageIndex":10},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107435,"frames":[{"imageOffset":3912,"imageIndex":8}]},{"id":1107436,"frames":[{"imageOffset":3912,"imageIndex":8}]},{"id":1107496,"frames":[{"imageOffset":19396,"imageIndex":0},{"imageOffset":441888,"imageIndex":11},{"imageOffset":368032,"imageIndex":11},{"imageOffset":358060,"imageIndex":11},{"imageOffset":359704,"imageIndex":11},{"imageOffset":101884,"imageIndex":5},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107497,"frames":[{"imageOffset":8208,"imageIndex":0},{"imageOffset":33396,"imageIndex":8},{"imageOffset":33702876,"imageIndex":12},{"imageOffset":33736080,"imageIndex":12},{"imageOffset":33703340,"imageIndex":12},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107498,"frames":[{"imageOffset":317392,"imageIndex":13},{"imageOffset":422636,"imageIndex":13},{"imageOffset":386768,"imageIndex":13},{"imageOffset":382332,"imageIndex":13},{"imageOffset":446084,"imageIndex":13},{"imageOffset":445796,"imageIndex":13},{"imageOffset":442824,"imageIndex":13},{"imageOffset":1523796,"imageIndex":13},{"imageOffset":1522684,"imageIndex":13},{"imageOffset":1522472,"imageIndex":13},{"imageOffset":347492,"imageIndex":14},{"imageOffset":346396,"imageIndex":14},{"imageOffset":363644,"imageIndex":14},{"imageOffset":363152,"imageIndex":14},{"imageOffset":345780,"imageIndex":14},{"imageOffset":363644,"imageIndex":14},{"imageOffset":363152,"imageIndex":14},{"imageOffset":345020,"imageIndex":14},{"imageOffset":363644,"imageIndex":14},{"imageOffset":33690976,"imageIndex":12},{"imageOffset":33688120,"imageIndex":12},{"imageOffset":33763712,"imageIndex":12},{"imageOffset":357256,"imageIndex":11},{"imageOffset":356796,"imageIndex":11},{"imageOffset":33801936,"imageIndex":12},{"imageOffset":1118656,"imageIndex":12},{"imageOffset":348716,"imageIndex":5},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107499,"frames":[{"imageOffset":179588,"imageIndex":0},{"imageOffset":42420,"imageIndex":8},{"imageOffset":33692352,"imageIndex":12},{"imageOffset":33703340,"imageIndex":12},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107500,"name":"com.apple.CFStream.LegacyThread","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":1079928,"imageIndex":1},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107501,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":5508,"imageIndex":0},{"imageOffset":7196,"imageIndex":0},{"imageOffset":30360,"imageIndex":1},{"imageOffset":47500,"imageIndex":1},{"imageOffset":127944,"imageIndex":1},{"imageOffset":2599120,"imageIndex":15},{"imageOffset":428592,"imageIndex":7},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107502,"frames":[{"imageOffset":19396,"imageIndex":0},{"imageOffset":441888,"imageIndex":11},{"imageOffset":368032,"imageIndex":11},{"imageOffset":358060,"imageIndex":11},{"imageOffset":359704,"imageIndex":11},{"imageOffset":32206780,"imageIndex":12},{"imageOffset":33703340,"imageIndex":12},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"triggered":true,"id":1107503,"threadState":{"x":[{"value":0},{"value":12},{"value":0},{"value":4815586688},{"value":4118255335},{"value":6132395143},{"value":4815586691},{"value":352},{"value":6491756752},{"value":2},{"value":1},{"value":0},{"value":3839723657},{"value":2246822519},{"value":4609545392},{"value":6132395336},{"value":0},{"value":4754574944},{"value":0},{"value":6132394280},{"value":6132394304},{"value":6132394288},{"value":4815586944},{"value":68719460620},{"value":0},{"value":4754574960},{"value":0},{"value":18446744073709551615},{"value":4815587376}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4663998388},"cpsr":{"value":1610616832},"fp":{"value":6132395408},"sp":{"value":6132394272},"esr":{"value":2449473540,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4683102124,"matchesCrashFrame":1},"far":{"value":18446744073709551615}},"frames":[{"imageOffset":20559788,"imageIndex":12},{"imageOffset":1456052,"imageIndex":12},{"imageOffset":29847700,"imageIndex":12},{"imageOffset":29850440,"imageIndex":12},{"imageOffset":29987028,"imageIndex":12},{"imageOffset":29989468,"imageIndex":12},{"imageOffset":33703340,"imageIndex":12},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107504,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":8784,"imageIndex":0},{"imageOffset":698192,"imageIndex":1},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107505,"frames":[{"imageOffset":19396,"imageIndex":0},{"imageOffset":441888,"imageIndex":11},{"imageOffset":368032,"imageIndex":11},{"imageOffset":358060,"imageIndex":11},{"imageOffset":359704,"imageIndex":11},{"imageOffset":367220,"imageIndex":14},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107506,"name":"pool-spawner","frames":[{"imageOffset":8208,"imageIndex":0},{"imageOffset":33396,"imageIndex":8},{"imageOffset":824204,"imageIndex":11},{"imageOffset":63296,"imageIndex":11},{"imageOffset":63540,"imageIndex":11},{"imageOffset":591876,"imageIndex":11},{"imageOffset":589880,"imageIndex":11},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]},{"id":1107507,"name":"gmain","frames":[{"imageOffset":19396,"imageIndex":0},{"imageOffset":441888,"imageIndex":11},{"imageOffset":368032,"imageIndex":11},{"imageOffset":358060,"imageIndex":11},{"imageOffset":358232,"imageIndex":11},{"imageOffset":366168,"imageIndex":11},{"imageOffset":589880,"imageIndex":11},{"imageOffset":6752,"imageIndex":8},{"imageOffset":3932,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7409360896,
    "size" : 212992,
    "uuid" : "061cf881-ce66-3b63-b9cc-4e266e382de7",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6494576640,
    "size" : 4538368,
    "uuid" : "f0ad1367-1bae-3957-a3f2-091e049db82d",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6955696128,
    "size" : 36864,
    "uuid" : "c45c68be-4df0-35ea-962f-27f5512ba09c",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6533013504,
    "size" : 25665536,
    "uuid" : "e498d63d-b35e-3a36-a2cf-688254c73835",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6622588928,
    "size" : 16912384,
    "uuid" : "1269aa5d-0334-3702-a396-3c33969dfb13",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/SwiftUI",
    "name" : "SwiftUI"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4343070720,
    "size" : 3194880,
    "uuid" : "718df039-9948-3810-ad3f-e03df0869ae1",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/62DB6D2E-E078-4E2D-9ED4-5A867AE00248\/UTM SE.app\/UTM SE",
    "name" : "UTM SE"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4348313600,
    "size" : 360448,
    "uuid" : "8836f397-3370-320c-baed-76edf7977ab0",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6519914496,
    "size" : 3166208,
    "uuid" : "b2622a6a-ae26-3f10-b9cb-19c1c113f29b",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8374697984,
    "size" : 49152,
    "uuid" : "4ef97b53-dd38-3d5b-bb8d-6edd490355af",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6491463680,
    "size" : 286720,
    "uuid" : "70fbc63e-c446-3bd3-a3bd-6f022317469b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6649131008,
    "size" : 172032,
    "uuid" : "d5c75724-93fc-3bdd-a6c6-beabc251059b",
    "path" : "\/System\/Library\/PrivateFrameworks\/AudioSession.framework\/AudioSession",
    "name" : "AudioSession"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364566528,
    "size" : 1589248,
    "uuid" : "a63140f0-57dd-3231-94ea-22ca8d2db79b",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/62DB6D2E-E078-4E2D-9ED4-5A867AE00248\/UTM SE.app\/Frameworks\/glib-2.0.0.framework\/glib-2.0.0",
    "name" : "glib-2.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4662542336,
    "size" : 39092224,
    "uuid" : "20b12679-c384-396d-b098-ae6baed05e43",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/62DB6D2E-E078-4E2D-9ED4-5A867AE00248\/UTM SE.app\/Frameworks\/qemu-ppc-softmmu.framework\/qemu-ppc-softmmu",
    "name" : "qemu-ppc-softmmu"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4366876672,
    "size" : 2293760,
    "uuid" : "f15f5c99-c887-31e7-ada5-dbf6fc0b5065",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/62DB6D2E-E078-4E2D-9ED4-5A867AE00248\/UTM SE.app\/Frameworks\/crypto.1.1.framework\/crypto.1.1",
    "name" : "crypto.1.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372529152,
    "size" : 1327104,
    "uuid" : "4bb98f76-ac0e-368b-8c58-28d331ad68ae",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/62DB6D2E-E078-4E2D-9ED4-5A867AE00248\/UTM SE.app\/Frameworks\/spice-server.1.framework\/spice-server.1",
    "name" : "spice-server.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6503055360,
    "size" : 5001216,
    "uuid" : "9534b29d-1aad-3a47-ba01-11aa2bfcc10f",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/CFNetwork",
    "name" : "CFNetwork"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6491144192,
  "size" : 2456666112,
  "uuid" : "15989fc7-7698-3890-b8bf-688a90e6777c"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=900.3M resident=0K(0%) swapped_out_or_unallocated=900.3M(100%)\nWritable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                    4112K       36 \nColorSync                           96K        6 \nCoreAnimation                      208K       11 \nFoundation                          16K        1 \nImage IO                            32K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           601.9M      246 \nMALLOC guard page                  192K       12 \nSQLite page cache                  128K        2 \nSTACK GUARD                        320K       20 \nStack                             11.1M       20 \nVM_ALLOCATE                      309.8M       22 \nVM_ALLOCATE (reserved)             1.0G        3         reserved VM address space (unallocated)\n__AUTH                            4536K      523 \n__AUTH_CONST                      25.6M      692 \n__DATA                            29.0M      757 \n__DATA_CONST                      26.8M      730 \n__DATA_DIRTY                      2793K      574 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       195.2M       77 \n__OBJC_CONST                      6480K      495 \n__OBJC_RO                         90.5M        1 \n__OBJC_RW                         3392K        1 \n__TEXT                           705.2M      781 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      189.6M       53 \nshared memory                     2096K        5 \n===========                     =======  ======= \nTOTAL                              3.2G     5083 \nTOTAL, minus reserved VM space     2.2G     5083 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_HAMMER" : "610950f91cbd7a245337216e"
      },
      "deploymentId" : 250000110
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "60ef663fa2f864203caf575c"
      },
      "deploymentId" : 250000055
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 250000013
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "610c8690fc54bc338984020b"
      },
      "deploymentId" : 250000156
    },
    {
      "rolloutId" : "60509d56f2766876dee21c11",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "610c8c6137f5d11121dcd240",
        "SIRI_UNDERSTANDING_NL" : "610c8c6837f5d11121dcd258",
        "SIRI_UNDERSTANDING_MORPHUN" : "610c8c5afc54bc338984030c",
        "SIRI_EXPERIENCE_CAM" : "610c8c6dfc54bc338984033b"
      },
      "deploymentId" : 250000346
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 250000007
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "611ad37537f5d11121dcd81b"
      },
      "deploymentId" : 250000164
    },
    {
      "rolloutId" : "602c34a3046661000c9ebdde",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "6123dc5a71e2b37fe06a5858"
      },
      "deploymentId" : 250000380
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "577038e4-446f-429a-899c-2e92b4b1dc9d",
      "experimentId" : "60c785f07aa5af21f0101872",
      "deploymentId" : 500000001
    },
    {
      "treatmentId" : "f2b19ff9-b1e3-42c4-8ad0-2ad670b8a61c",
      "experimentId" : "60c7880b7aa5af21f0101873",
      "deploymentId" : 500000001
    }
  ]
}
}

</details>

**Comment by osy** [comment]
@Vishram1123 that's not a crash log it should have a name like `UTM-2021-08-31-103447.ips`

**Comment by Vishram1123** [comment]
UTM SE-2021-08-31-090039.ips is the name of the log I pasted there

**Comment by AFellowSpeedrunner** [comment]
Anyone got a fix for this? I am also having problems with UTM on iOS 15 running any kind of PowerPC machine.

**Comment by osy** [comment]
@AFellowSpeedrunner can you provide a crash log and debug log and open a new issue? This issue is closed.

**Comment by nguyenthienminh** [comment]
Did anyone got out a fix? I also got the same problem.

**Comment by ap46281** [comment]
Been a few months but I’m still having the same troubles. Anybody find a fix?

**Comment by Bastian2024** [comment]
Issue still persists when booting to install Mac OS X Developer Preview 3
