### ISSUE TITLE
Cannot "Clear" USB Drive

### ISSUE THREAD

**Issue by dimaqq** [utmapp/UTM#5708]
**Describe the issue**  
I'm unable to clear the USB drive image:

* click on a powered-off vm
* edit
* go to USB drives
* the ISO image is shown in the path
* click clear (path disappears)
* click save (modal gets closed)
* edit again
* the path is there

This has the effect of my VM stuck on booting from the installation media.

**Configuration**  
* UTM Version: 4.3.5 (87)
* macOS Version: 13.5.1
* Mac Chip (Intel, M1, ...): M2

![Screenshot 2023-09-16 at 14 08 18](https://github.com/utmapp/UTM/assets/662249/292d2cfa-4bfc-4e31-86f2-e9de66892122)

Additionally, I can get this error to pop up after restarting/reinstalling UTM:

![Screenshot 2023-09-16 at 14 07 58](https://github.com/utmapp/UTM/assets/662249/3e4cba41-facf-4a87-94a5-0d84647d9c50)

As a work-around, I can clone the VM and run the clone instead.

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/12639895/config.plist.zip)

**Comment by osy** [comment]
I think this was fixed in v4.4 beta, can you try it?

**Comment by dimaqq** [comment]
I've tried 4.4.1 (89) and the first issue is still there:
- clicking "clear" appears to remove the ISO
- save
- edit again: the iso is still shown as attached

**Comment by dimaqq** [comment]
However, I can clear from drop-down on the main page (vm listing), that works.
