### ISSUE TITLE
black screen after update 4.4.5

### ISSUE THREAD

**Issue by Fischmuetze** [utmapp/UTM#5961]
**Describe the issue**  
After update on 4.4.5 all machines runs into a black screen (but runs so far, Linux VMs are able to access via ssh and Windows 11 make sounds after start) 

**Configuration**  
* UTM Version:  4.5.5.
* macOS Version:  13.6.2 (22G320)
* Mac Chip (Intel, M1, ...): M1 Pro, 32GB

**Crash log**  
there is no crash in this sense

Update:
roll back to 4.4.4. and all works fine. So there is definitely an issue withe the 4.4.5

**Comment by osy** [comment]
That's weird, there's no code change in 4.4.5. Any chance you can try 4.4.5 again just in case it's a weird one off issue?

**Comment by hs123org** [comment]
Same issue for me. Upgraded from 92 to 4.4.5 (94) via homebrew on M1 Macbook Pro.
VM is Debian with GUI. qemu is configured to use virtio-ramfb-gl.

Using any of the -gl options on the Display config page results in a blank screen. When changing to virtio-ramfb (no -gl) it works, albeit without acceleration.

**Comment by osy** [comment]
Oh it seems like I had forgotten about this commit: https://github.com/utmapp/UTM/commit/917f35759d9efafade6775adfef57389cbab4e29

it's probably causing the issue

Ugh okay

**Comment by Fischmuetze** [comment]
> That's weird, there's no code change in 4.4.5. Any chance you can try 4.4.5 again just in case it's a weird one off issue?

Can repeat that. Starting 4.4.4. all is fine starting 4.4.5. runs in a black screen.
Noticeable: with 4.4.5. the UTM boot logo, " Start boot optoions" etc. are also not displayed

**Comment by osy** [comment]
Okay I'm pulling the release.

**Comment by osy** [comment]
Should be fixed in 4.4.6

**Comment by albertyw** [comment]
Did you pull the wrong release?  I see https://github.com/utmapp/UTM/releases/tag/v4.4.5 still exists but https://github.com/utmapp/UTM/releases/tag/v4.4.6 disappeared.

**Comment by osy** [comment]
No I did a stupid thing and decided that it should be named 4.4.6 but internally versioned as 4.4.5. Don't ask. Anyways that seems to have broken AltStore so I just renamed it back to 4.4.5 and hope that a month from now, nobody will remember this fuck up.

**Comment by Fischmuetze** [comment]
> No I did a stupid thing and decided that it should be named 4.4.6 but internally versioned as 4.4.5. Don't ask. Anyways that seems to have broken AltStore so I just renamed it back to 4.4.5 and hope that a month from now, nobody will remember this fuck up.

imho a bad decision since the 4.4.6 wasn't reach the brew repositories
In consequence all users that already have installed the "old" bugged 4.4.5 still will waiting endless for a fix, as the fixed 4.5.5. version is tagged as 4.4.5 and will not force an update. Not each of this user will understand that they have to force a reinstall via brew reinstall utm, since they would have to read for this the thread
