### ISSUE TITLE
Cannot access TPM data.

### ISSUE THREAD

**Issue by valentinegb** [utmapp/UTM#6637]
## Describe the issue

The other day I tried to create a Windows VM and failed since trying to run it resulted in an error, "Cannot access TPM data." The next day I tried again and it miraculously worked! Today however, I went to launch the same VM from the day before and was once again met with "Cannot access TPM data."

## Configuration

- UTM Version: 4.5.4 (100)
- macOS Version: 15.1 Beta (24B5035e)
- Mac Chip (Intel, M1, ...): M1

## Debug log

Attempting to enable "Debug Logging" for the VM fails with the error "The file couldn’t be opened."

## Upload VM

[config.plist.zip](https://github.com/user-attachments/files/16803250/config.plist.zip)

**Comment by valentinegb** [comment]
Today it seems to work fine, not closing this yet though since I don't expect it to keep working. Reminds me of the "can't print on Tuesdays" bug lol

**Comment by jsondergaard** [comment]
I'm facing the same issue, also on the 15.1 beta.

**Comment by Grrrolf** [comment]
Same here, also macOS 15.1 beta.

**Comment by nothingneko** [comment]
same here, no Windows VM will load

**Comment by mannnyyy** [comment]
Hi, same here. On macOS 15.0 final.

**Comment by ag10889** [comment]
Same here, just updated from 4.4.5 to 4.5.4 to match thread. Running 15.0 final. M1 chip. Attempting to Reset UEFI / QEMU sub menu results in "The file couldn't be opened".

**Comment by lcarson-2002** [comment]
> Same here, just updated from 4.4.5 to 4.5.4 to match thread. Running 15.0 final. M1 chip. Attempting to Reset UEFI / QEMU sub menu results in "The file couldn't be opened".

Same issue here.

**Comment by davidfrankovertica** [comment]
Same issue here, macOS 15.0, M2 Max

**Comment by lcarson-2002** [comment]
The problem is repeatable. Every time I unplug my macBook Pro (M1 Ultra) from my home office and plug it into my work office (and vice versa) it happens upon plugin at the other location. This requires a reboot to clear the condition.

**Comment by KlementTobias** [comment]
Same issue here

**Comment by Boogimoogi** [comment]
Same issue here.

**Comment by Dekko2205** [comment]
Hi,
I confirm that the reboot works for me too but it is not a comfortable solution.
Has anyone found a better method?

**Comment by osy** [comment]
Have you updated to 15.0.1?

**Comment by Dekko2205** [comment]
> Have you updated to 15.0.1?

I have 15.0

**Comment by osy** [comment]
Update to 15.0.1. That's your better method.

**Comment by Dekko2205** [comment]
> Update to 15.0.1. That's your better method.

:-) Thanks. I'll try tonight. I'll give you feedback in few days.

**Comment by rkrenzis** [comment]
Issue present on 15.0.1 on m1 Pro.  Attempting to "Reset UEFI Variables" under QEMU submenu results in "The file could not be opened."  Rebooting temporarily fixes the issue.  My machine has been up for 1 day 14 minutes.

**Comment by osy** [comment]
Can someone provide a sysdiagnose? Note that it may contain identifiers but it will only be used in diagnosing the issue and then be deleted. You can send the dump to dev at getutm dot app

**Comment by HenkPoley** [comment]
Hmm, after a host reboot the 'Cannot access TPM data' message is gone.

Settings > QEMU > Reset UEFI vars, also give an access denied error before the reboot.

**Comment by Dekko2205** [comment]
> > Update to 15.0.1. That's your better method.
> 
> :-) Thanks. I'll try tonight. I'll give you feedback in few days.

I have no problem anymore. I don't know why.

Sequoia 15.1

**Comment by kiranb4352** [comment]
Same problem here

**Comment by wenxdeng** [comment]
MacOS 15.0.1 
UTM 4.5.4 (100)
VM: Windows 11 ARM

I have the same problem, and reboot MacOS can temporarily fix it.

**Comment by 8bit-coder** [comment]
MacOS 15.0.1 (M3 Pro Late '23 MacBook Pro)
UTM 4.5.4 (100)
VM: Windows 11 ARM

Same exact problem here. Why isn't this being fixed?

**Comment by osy** [comment]
@8bit-coder https://github.com/utmapp/UTM/issues/6637#issuecomment-2404278150

**Comment by yaroslavyaroslav** [comment]
I can confirm that reboot solved the issue for me.

**Comment by Kataki-Takanashi** [comment]
Same issue here, MacOS Sequoia 15.0 checking Reset UFEI variables and then saving brings up the message "The file couldn’t be opened." After I hit "ok" the box is unchecked.

Also cant add a shared directory to a MacOS VM it says the same "The file couldn’t be opened." message.

**Comment by tech4him1** [comment]
It looks like this is linked to #6639.

Quoting the relevant text from the link posted by @tonilampela in https://github.com/utmapp/UTM/issues/6639#issuecomment-2431688538:

> We've tracked down the problem to an issue with macOS 15.0 (Sequoia). Technically this involves their "Bookmark" resolution code ... It also only happens a little while after a device restart (about 2-6 hours usually), so it's a bit of a "heisenbug", very difficult to track down. Restarting your device or logging out/in also fixes things because it restarts the process which handles bookmarks on Apple's side. ...
> 
> Apple have acknowledged the issue and believe they have already fixed it in macOS 15.1 Beta 4. So updating to that beta version of macOS should fix this too.
>
> ~ https://www.reddit.com/r/strongbox/comments/1fo7z20/comment/lp5mtnu/

So rebooting should be a temporary fix to get a VM running; or upgrade to macOS 15.1 RC.

**Comment by VGerris** [comment]
> > Hi, same here. On macOS 15.0 final.
> 
> -->>> RESOLVED : by reseting UEFI settings in VM Settings / QEMU sub menu

I got 'This file couldn't be opened' which I suppose is the root cause. I just shut down the VM normally.

**Comment by osy** [comment]
@VGerris Have you updated to 15.1 yet?

**Comment by VGerris** [comment]
> @VGerris Have you updated to 15.1 yet?

No, I was running 15.01, didn't see the update yet. Saw it now and running update.

**Comment by indexxing** [comment]
> It looks like this is linked to #6639.
> 
> Quoting the relevant text from the link posted by @tonilampela in [#6639 (comment)](https://github.com/utmapp/UTM/issues/6639#issuecomment-2431688538):
> 
> > We've tracked down the problem to an issue with macOS 15.0 (Sequoia). Technically this involves their "Bookmark" resolution code ... It also only happens a little while after a device restart (about 2-6 hours usually), so it's a bit of a "heisenbug", very difficult to track down. Restarting your device or logging out/in also fixes things because it restarts the process which handles bookmarks on Apple's side. ...
> > Apple have acknowledged the issue and believe they have already fixed it in macOS 15.1 Beta 4. So updating to that beta version of macOS should fix this too.
> > ~ https://www.reddit.com/r/strongbox/comments/1fo7z20/comment/lp5mtnu/
> 
> So rebooting should be a temporary fix to get a VM running; or upgrade to macOS 15.1 RC.

Thanks for the context! I was having this same issue, I may try rebooting now.

**Comment by Seganation** [comment]
I'm using Mac M3 with UTM Windows 11 i had the same problem "Cannot access TPM data." to fix it I went into the configuration of the VM that wasn't working in the UTM app i went into QEMU and unticked "TPM 2.0 Device" then I clicked save and it worked fine after that

**Comment by RalfBiNe** [comment]
"Cannot access TPM data." - Same for me with Mac OS Seaquoia 15.0.1 on a M1 Mac Book Air (2020) and Windows 11 Pro in UTM. A Mac reboot fixed the issue.

**Comment by wh173d3v11** [comment]
### **Restarting MAC solving the issue.**

**Comment by 010x000000** [comment]
I fixed the problem locating VM file in Finder, and giving "write and read" permissions to all users and groups listed. Sonoma 14.7.1

**Comment by zbit-io** [comment]
> ### **Restarting MAC solving the issue.**

it works on me

**Comment by directordash** [comment]
Still an issue, for me.
On first setup I get "The file couldn't be opened" with ANY CrystalFetch ISO image (Windows 11 for ARM).
If I quit the app, and reopen, the VM will be there, but then attempting to run it results in the "Cannot access TPM data".

- Have tried on 4.6.5, and also on the latest TestFlight version. Literally can't run anything - virtualized or emulated.
- Running Sonoma 14.7.1, with Full Disk Access enabled for UTM.
